name: Release

on:
  release:
    types: [published]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Build
        run: ./pyinstaller/build-windows.bat
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: dist/epiccli-ui.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Build
        run: |
          chmod +x pyinstaller/build-macos.sh
          ./pyinstaller/build-macos.sh
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: dist/epiccli-ui
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Build
        run: |
          chmod +x pyinstaller/build-linux.sh
          ./pyinstaller/build-linux.sh
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: dist/epiccli-ui
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
